# Site settings
title: Kabir Goel
description: >
    I'm a 14 year old programmer, Unix geek and quizzer from New Delhi, India.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://kbrgl.github.io/" # the base hostname & protocol for your site
twitter_username: notkabir
github_username:  kbrgl

# Build settings
markdown: kramdown
